version: 2
jobs:
  build:
    working_directory: /go/gopherjs
    docker:
      # We have a custom installation of Go below so this version is (largely) irrelevant.
      - image: circleci/golang:1.10

    environment:
      SOURCE_MAP_SUPPORT: false
      NVM_VERSION: v0.33.9
      GO_VERSION: 64205cd4b6d48432fdcbe2127d45e4f786468ff3
      NODE_VERSION: 10.0.0

    steps:
      - checkout

      - run: |
          echo 'export GO111MODULE=on' >> $BASH_ENV
          git --version

      - run: |
          # Install nvm.
          git clone https://github.com/creationix/nvm.git $HOME/.nvm
          cd $HOME/.nvm && git checkout $NVM_VERSION
          echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
          echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV

      - run: |
          # Install our own local Go version; we need src/path/filepath to be writable for certain tests.
          mkdir $HOME/go
          if [[ "$GO_VERSION" =~ go* ]]
          then
            curl https://storage.googleapis.com/golang/$GO_VERSION.linux-amd64.tar.gz | tar -C $HOME -xz
          else
            sudo apt-get -y -qq update < /dev/null > /dev/null
            sudo apt-get -y -qq install python-pip < /dev/null > /dev/null
            pip install -q awscli
            export PATH=$HOME/.local/bin:$PATH
            aws s3 cp "s3://io.myitcv.gobuilds/linux_amd64/$GO_VERSION.tar.gz" - | tar -C $HOME -xz
          fi
          chmod a+w $HOME/go/src/path/filepath
          echo 'export PATH="$HOME/go/bin:$PATH"' >> $BASH_ENV

      - run: |
          # Per https://github.com/gopherjs/gopherjs/pull/687.
          echo 'ulimit -s 10000' >> $BASH_ENV

      - run: |
          # Setup our required Node version now that nvm is installed.
          nvm install $NODE_VERSION node
          nvm alias default $NODE_VERSION

      - run: |
          # Verify our environment setup.
          which node
          which go
          node --version
          go version
          go env

      - run: |
          # Per https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md.
          npm install --global node-gyp
          cd node-syscall && node-gyp rebuild && mkdir -p $HOME/.node_libraries/ && cp build/Release/syscall.node $HOME/.node_libraries/syscall.node

          # this gives us the repo-local binaries we require
          npm install

      - run: |
          go install github.com/gopherjs/gopherjs

      - run:
          # because this is a long-running test suite
          no_output_timeout: 30m
          command: |
              echo ">> Regenerate compiler/prelude"
              go generate github.com/gopherjs/gopherjs/compiler/prelude

              echo ">> Ensure there are no variations from the git commit"
              diff -u <(echo -n) <(git status --porcelain)

              echo ">> Ensure all go code is well formatted."
              diff -u <(echo -n) <(gofmt -d .)

              echo ">> Vetting github.com/gopherjs/gopherjs"
              go vet .

              echo ">> vet all packages except tests"
              go vet $(go list ./... | grep -v github.com/gopherjs/gopherjs/tests)

              echo ">> All those packages should have // +build js."
              diff -u <(echo "github.com/gopherjs/gopherjs/compiler/natives") <(go list ./compiler/natives/...)

              echo ">> Should build successfully (can't run tests, since only client is supported)."
              gopherjs install -v net/http

              echo ">> Run the core gopherjs tests; exclusions take from .std_test_pkg_exclusions."
              gopherjs test --minify -v --short github.com/gopherjs/gopherjs/tests/... $(go list std | grep -v -x -f .std_test_pkg_exclusions)

              echo ">> Race tests."
              go test -v -race ./...

              echo ">> Non-minified gopherjs tests should also work."
              gopherjs test -v fmt
